runtime: php
env: flex

runtime_config: document_root: public

# Ensure we skip ".env", which is only for local development
skip_files: 
    - .env

automatic_scaling:
    min_num_instances: 1
    max_num_instances: 1

resources:
    cpu: 4
    memory_gb: 64
    disk_size_gb: 100

env_variables:
    # Put production environment variables here.
    APP_DEBUG: true
    APP_ENV: production
    APP_KEY: base64:FyIMaNzd/mYRG3jg1qk1jBvlu+N6K8WCtq8nUGsIzTc=
    APP_NAME: "StockLaporan-Datasync"

    LOG_LEVEL: debug
